version: '3.8'

services:
  backend:
    build: 
      context: ./FastAPIBackend
      args:
        ACCESS_KEY: ${ACCESS_KEY}
        SECRET_KEY: ${SECRET_KEY}
    image: image-classification-app-back-end
    ports:
      - "80:80"
    networks:
      - my_network

  requester:
    build: ./Frontend
    image: image-classification-app-front-end
    ports:
      - 8501:8501
    networks:
      - my_network

networks:
  my_network:
